### ISSUE TITLE
200 success for no changes in repositioning

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsServer#104]

**Comment by TPausL** [comment]
der vergleich ob gleich ist reicht nicht wenn aktuelle pos zB 3 ist und die letzte man 7 reintut ändert sich nichts man bekommt aber 200 zurück

**Comment by Jozys** [comment]
> der vergleich ob gleich ist reicht nicht wenn aktuelle pos zB 3 ist und die letzte man 7 reintut ändert sich nichts man bekommt aber 200 zurück

Oh ja natürlich. Kümmere mich darum.
