### ISSUE TITLE
return all lights changing position

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsServer#105]
@Jozys macht das was bei dir kaputt wenn ich das ändere? Da sich ja in der regel mehrere lichter ändern sollten wir auch alle zurück geben

**Comment by Jozys** [comment]
> @Jozys macht das was bei dir kaputt wenn ich das ändere? Da sich ja in der regel mehrere lichter ändern sollten wir auch alle zurück geben

Da ich das bisher nur teilweise im Frontend  implementiert habe nicht.

**Comment by TPausL** [comment]
ok dann mache ich das mal kurz wei bei mir ist gerade komplettes chaos wenn ich nen lihct verschiebe

**Comment by Jozys** [comment]
okay
