### ISSUE TITLE
lowercase tags

### ISSUE THREAD

**Issue by TPausL** [ProjektKursInfo/DevLightsServer#99]

**Comment by Jozys** [comment]
Heißt wir erlauben auch nur lowercase tags oder wie?

**Comment by TPausL** [comment]
ja bzw wäre wahrscheinlich gut wenn wir große automatisch kleiner machen und auch leerzeichen erlauben aber wegmachen

**Comment by Jozys** [comment]
okay. leerzeichen etc. entfernen lässt sich theoretisch auch im frontend machen, aber was meinst du wäre besser frontend oder backend?

**Comment by TPausL** [comment]
immer backend

der nutzer soll möglichst wenig stress haben
außerdem müssen wir es dann nur einmal machen
heißt der "letzte nutzer" kann einfach 'Moin was geht?' z.B. in die app eingeben und dann bekommt man 'moinwasgeht' zurück

**Comment by Jozys** [comment]
okay alles klar, bin eh gerade am server am arbeiten, baue das dann ein :)

**Comment by TPausL** [comment]
sollten wir sonder zeichen wegmachen?

**Comment by Jozys** [comment]
ja können wir eigentlich rausnehmen

umlaute wie ä.ö und ü zulassen, ja oder nein?

**Comment by TPausL** [comment]
würde nein sagen basically nur a-z und 0-9

**Comment by TPausL** [comment]
wollen wir jetzt zusammen was machen?

**Comment by Jozys** [comment]
> wollen wir jetzt zusammen was machen?
> 
> 

Sorry war weg.
Können vllt später was am Server machen.

**Comment by Jozys** [comment]
alles was nicht a-z oder 0-9 ist replace mit "" oder request abblocken?
